### ISSUE TITLE
Data and charts disappeared and cannot get them back. 

### ISSUE THREAD

**Issue by eclmwb** [WelSimLLC/WelSim-App#2]

**Comment by eclmwb** [comment]
I closed the right hand tabular data and charts and now I am unable to get the window open to import data. I've tried uninstalling and re-installing program. Every time I re-open the program, I am unable to access Data tables and charts.

**Comment by getwelsim** [comment]
There are two ways  to get the windows back: 
1. Menu -> View -> Windows -> toggle on the item
2. Right mouse button click on the Toolbar area, and select the expected window to display or hide.

**Comment by getwelsim** [comment]
Close this issue. 
If you have any further problems, feel free to reopen or submit a new one.
