### ISSUE TITLE
Welsim 2.3 error

### ISSUE THREAD

**Issue by ChrisNabold** [WelSimLLC/WelSim-App#3]
I just downloaded Welsim 2.3 and tried to run the test example hole_plate.wsdb.
I recieve the following error message: (see below)
[Welsim 2.3 error.txt](https://github.com/WelSimLLC/WelSim-App/files/9196481/Welsim.2.3.error.txt)
returning Welsim to V2.2 the problem runs ok.

**Comment by getwelsim** [comment]
Thank you for your feedback. 
We can reproduce this issue from a resumed old project. In the R2.3, re-assigning the material to the geometry part probably solves the problem. Please let us know if the problem persists. We will patch the R2.3 with the added error message for this scenario.

**Comment by getwelsim** [comment]
R2.3 has been patched for this scenario. An error message will be prompted when invalid material data is found.

**Comment by ChrisNabold** [comment]
Thank you for the info. I downloaded new version.

Now I receive the error message: Error: can not allocate material model  (ID=10) for the part “Cut”.

But whatever I try I can not reassign new properties to the Materials>Material

If I rightclick on Material and try Edit: nothing happens

I also tried Add Material: just a new material Material1 is created but I can not assign new values.

 

Can you please help

Best regards

Chris

**Comment by getwelsim** [comment]
Thank you for your comments. 
We are looking at this material "Edit" problem. At this moment, you can double-click the material object to edit.

**Comment by getwelsim** [comment]
This issue has been fixed. Close for now, but feel free to reopen or start a new thread if the issue persists.
