### ISSUE TITLE
curvefitter的使用问题

### ISSUE THREAD

**Issue by Argonnn123** [WelSimLLC/WelSim-App#4]
目前curvefitter软件只有内置的公式方程，能否添加一个功能，能够输入自定义的函数方程，来进行非线性曲线拟合。谢谢！

**Comment by getwelsim** [comment]
Thank you for using Curvefitter and for your valuable suggestions. 

Since every function has its own characteristics, the computational algorithms could be different. Fully supporting arbitrary functions needs a large amount of development and testing resources. However, we will look for a solution for this. At this moment, we can add your specific functions to the Curvefitter, this may only take a few days, even less.

**Comment by Argonnn123** [comment]
非常感谢您的回复！
特定函数已添加到附件中，是Schulz-Flory最可能分布的推导公式。
如暂时无法实现该功能，可按下述公式添加，也可暂时使用。
谢谢！

[Schulz-Flory最可能分布的推导公式.pdf](https://github.com/WelSimLLC/WelSim-App/files/9264372/Schulz-Flory.pdf)

y=a*ln(10)/b^2*exp(4.6*x-1/b*exp(2.3*x))+c*ln(10)/d^2*exp(4.6*x-1/d*exp(2.3*x))+e*ln(10)/f^2*exp(4.6*x-1/f*exp(2.3*x))+g*ln(10)/h^2*exp(4.6*x-1/h*exp(2.3*x))+i*ln(10)/j^2*exp(4.6*x-1/j*exp(2.3*x))

**Comment by Argonnn123** [comment]
另外，还需添加限定条件。
（1）参数a、c、e、g、i均是大于0，小于1。
（2）a+c+e+g+i=1。
（3）对于所有参数均需设置初始值。

**Comment by Argonnn123** [comment]
另外，还需添加限定条件。
（1）参数a、c、e、g、i均是大于0，小于1。
（2）a+c+e+g+i=1。
（3）对于所有参数均需设置初始值。

**Comment by getwelsim** [comment]
@Argonnn123 thank you for the details. This function is highly nonlinear and very sensitive to the test data. Do you have the fitable test data?

**Comment by getwelsim** [comment]
@Argonnn123 For all given conditions, the test data must be limited to a very small range. Do you have the test data that can match the given parameters?

**Comment by Argonnn123** [comment]
[测试数据.pdf](https://github.com/WelSimLLC/WelSim-App/files/9277900/default.pdf)
@getwelsim 
以上是相关的测试数据及参数设定，请参考！谢谢！

**Comment by getwelsim** [comment]
@Argonnn123 Thanks for the test data. We have added this Schulz-Flory function to the nightly build. There are also many features added at this time. The new version will be released this week.

**Comment by Argonnn123** [comment]
再一次感谢您的支持！
很期待本周的新版本！

**Comment by getwelsim** [comment]
Thanks. 
CurveFitter has been updated for the Schulz-Flory function. You are welcome to use and comment.

**Comment by Argonnn123** [comment]
已经下载使用过了，效果非常棒！非常感谢您的帮助！
但是有一点小疑问，关于系数a1,a2,a3,a4,a5相加，怎么能确定等于1？
![image](https://user-images.githubusercontent.com/110600745/184563955-92cfd3d6-7203-4495-abe2-208e84bc4ac2.png)
我这边没有给出限定条件，直接拟合出的结果系数之和为0.9951668。

**Comment by getwelsim** [comment]
@Argonnn123 Thanks for your feedback. If you use CurveFitter for publication, please consider citing WelSim. This can help us make better software. 
The sum_{a_i}=1 is determined by the test data. The fitting algorithm automatically finds the best parameters, and manually imposing the sum_{a_i} constraints may cause a convergence difficulty.

**Comment by Argonnn123** [comment]
@getwelsim 好的，能够理解！非常感谢！

**Comment by Argonnn123** [comment]
@getwelsim 软件真的太好用了！再一次表示感谢！如果来中国的话，很高兴带你们来游玩！

**Comment by getwelsim** [comment]
@Argonnn123 Thank you for your kind words and warm hospitality, we will visit China someday. If you think our products are useful, please consider referring to your surroundings or citing WelSim CurveFitter in your publication. I will be closing this post, feel free to reopen this if you have any further comments about this feature.
